#!/usr/bin/env bash

git fetch cyclejs

git checkout gh-pages

git merge cyclejs/master --no-commit

npm install

npm run bundle

git commit -am "Update bundle"

git push cyclejs gh-pages

git checkout -
